apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: gke-primary-pool-sa-cs-monitoring-wi-user
  namespace: acm-workshop-341-tenant
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop-341-tenant/IAMServiceAccount/gke-primary-pool
spec:
  resourceRef:
    name: gke-primary-pool
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:acm-workshop-341-tenant.svc.id.goog[config-management-monitoring/default]
