apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: primary
  namespace: acm-workshop-341-tenant
  annotations:
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/acm-workshop-341-tenant/ContainerCluster/gke
spec:
  clusterRef:
    name: gke
  initialNodeCount: 1
  location: us-east4
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    imageType: COS_CONTAINERD
    diskSizeGb: 100
    diskType: pd-ssd
    labels:
      gke.io/nodepool: primary
    machineType: n2d-standard-4
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    serviceAccountRef:
      name: gke-primary-pool
